In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 4, 9])

In [3]:
print(np.sum(x))

16


In [4]:
np.mean(x)

4.0

In [5]:
np.median(x)

3.0

In [10]:
z = np.zeros((3, 4))
print(z)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
z.dtype

dtype('float64')

In [12]:
X = np.full((3, 2), 5)

In [14]:
print(X)

[[5 5]
 [5 5]
 [5 5]]


In [15]:
X = np.eye(2)

In [16]:
print(X)

[[1. 0.]
 [0. 1.]]
